### PR TITLE
fix distinct for groups

### LINKED ISSUE #535: Bug: distinct() ignores groups
library(dplyr)
    library(dbplyr)

    memdb_frame(x = 1:2, y = 1) %>% 
      group_by(x) %>% 
      distinct(y)
    #> # Source:   lazy query [?? x 2]
    #> # Database: sqlite 3.33.0 [:memory:]
    #> # Groups:   x
    #>       y
    #>   <dbl>
    #> 1     1

    tibble(x = 1:2, y = 1) %>% 
      group_by(x) %>% 
      distinct(y)
    #> # A tibble: 2 x 2
    #> # Groups:   x [2]
    #>       x     y
    #>   <int> <dbl>
    #> 1     1     1
    #> 2     2     1

<sup>Created on 2020-11-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

    devtools::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       macOS Catalina 10.15.7      
    #>  system   x86_64, darwin17.0          
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_US.UTF-8                 
    #>  ctype    en_US.UTF-8                 
    #>  tz       UTC                         
    #>  date     2020-11-10                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version date       lib source        
    #>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
    #>  backports     1.2.0   2020-11-02 [1] CRAN (R 4.0.2)
    #>  bit           4.0.4   2020-08-04 [1] CRAN (R 4.0.1)
    #>  bit64         4.0.5   2020-08-30 [1] CRAN (R 4.0.2)
    #>  blob          1.2.1   2020-01-20 [1] CRAN (R 4.0.0)
    #>  callr         3.5.1   2020-10-13 [1] CRAN (R 4.0.2)
    #>  cli           2.1.0   2020-10-12 [1] CRAN (R 4.0.2)
    #>  crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.0)
    #>  DBI           1.1.0   2019-12-15 [1] CRAN (R 4.0.0)
    #>  dbplyr      * 2.0.0   2020-11-03 [1] CRAN (R 4.0.2)
    #>  desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.0)
    #>  devtools      2.3.2   2020-09-18 [1] CRAN (R 4.0.2)
    #>  digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.2)
    #>  dplyr       * 1.0.2   2020-08-18 [1] CRAN (R 4.0.1)
    #>  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.0)
    #>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.0)
    #>  fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.0)
    #>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
    #>  generics      0.1.0   2020-10-31 [1] CRAN (R 4.0.2)
    #>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
    #>  highr         0.8     2019-03-20 [1] CRAN (R 4.0.0)
    #>  htmltools     0.5.0   2020-06-16 [1] CRAN (R 4.0.1)
    #>  knitr         1.30    2020-09-22 [1] CRAN (R 4.0.2)
    #>  lifecycle     0.2.0   2020-03-06 [1] CRAN (R 4.0.0)
    #>  magrittr      1.5     2014-11-22 [1] CRAN (R 4.0.0)
    #>  memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.0)
    #>  pillar        1.4.6   2020-07-10 [1] CRAN (R 4.0.1)
    #>  pkgbuild      1.1.0   2020-07-13 [1] CRAN (R 4.0.1)
    #>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.0)
    #>  pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.0)
    #>  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.0)
    #>  processx      3.4.4   2020-09-03 [1] CRAN (R 4.0.2)
    #>  ps            1.4.0   2020-10-07 [1] CRAN (R 4.0.2)
    #>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.1)
    #>  R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.2)
    #>  Rcpp          1.0.5   2020-07-06 [1] CRAN (R 4.0.1)
    #>  remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.1)
    #>  rlang         0.4.8   2020-10-08 [1] CRAN (R 4.0.2)
    #>  rmarkdown     2.5     2020-10-21 [1] CRAN (R 4.0.2)
    #>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 4.0.0)
    #>  RSQLite       2.2.1   2020-09-30 [1] CRAN (R 4.0.2)
    #>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
    #>  stringi       1.5.3   2020-09-09 [1] CRAN (R 4.0.2)
    #>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
    #>  testthat      3.0.0   2020-10-31 [1] CRAN (R 4.0.2)
    #>  tibble        3.0.4   2020-10-12 [1] CRAN (R 4.0.2)
    #>  tidyselect    1.1.0   2020-05-11 [1] CRAN (R 4.0.0)
    #>  usethis       1.6.3   2020-09-17 [1] CRAN (R 4.0.2)
    #>  utf8          1.1.4   2018-05-24 [1] CRAN (R 4.0.0)
    #>  vctrs         0.3.4   2020-08-29 [1] CRAN (R 4.0.2)
    #>  withr         2.3.0   2020-09-22 [1] CRAN (R 4.0.2)
    #>  xfun          0.19    2020-10-30 [1] CRAN (R 4.0.2)
    #>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.0)
    #> 
    #> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

### PR DESCRIPTION
**Pull request by mgirlich**
Closes #535

### CODE REVIEW

File: tests/testthat/test-verb-distinct.R [hunk 1]
```diff
@@ -31,6 +31,11 @@ test_that("distinct doesn't duplicate colum names if grouped (#354)", {
   expect_equal(df %>% group_by(a) %>% distinct() %>% op_vars(), "a")
 })
 
+test_that("distinct respects groups", {
+  df <- memdb_frame(a = 1:2, b = 1) %>% group_by(a)
+  expect_equal(df %>% distinct(b) %>% collect(), df %>% collect())
```
Comment (hadley) [inline tests/testthat/test-verb-distinct.R:36]: I think a clearer test is:

```R
expect_equal(df %>% group_by(a) %>% distinct() %>% op_vars(), c("a", "b"))
```

That suggests the behaviour is about column membership, not the validity of the results.

**Comment by hadley** [comment]
Thanks!
