### PR TITLE
MS SQL ifelse() issue fix #93

### LINKED ISSUE #93: MS SQL mutate(ifelse()) translation not working
I'm running into an issue when using mutate and ifelse (or if) on a SQL Server backend. The following sample query:

```
df <- tbl(con, in_schema("schema", "table_name")) %>%
   mutate(field = ifelse(field %in% c('test1', 'test2', 'test3'), 'string1', 'string2') %>%
   collect()
```

... will give the following translation:
```
SELECT CASE WHEN (("field" IN ('test1', 'test2', 'test3')) = 'TRUE') THEN ('string1') 
            WHEN (("field" IN ('test1', 'test2', 'test3')) =  'FALSE') THEN ('string2') 
            END AS "field"
```

Which will return an error. The correct translation should be:
```
SELECT CASE WHEN ("field" IN ('test1', 'test2', 'test3')) THEN 'string1' 
            WHEN ("field" NOT IN ('test1', 'test2', 'test3')) THEN 'string2' 
            END AS "field"
```

Will correcting this in the mssql_if function create any issues in other queries, or is there a better way to do mutate(ifelse()) in mssql?

https://github.com/tidyverse/dbplyr/blob/477480e3c488fe6338ce5f142142d280dd61487b/R/db-odbc-mssql.R#L225

### PR DESCRIPTION
**Pull request by edgararuiz**
Fixes #93 

Reverted to using CASE WHEN for all condition operations.  This meant that `mssql_logical_infix()` is not needed any longer.  This will mean longer SQL statements, but it will accommodate more cases than before.

Tests:

```
library(odbc)                                                                                       
library(DBI)                                                                                        
library(dplyr, warn.conflicts = FALSE)                                                              
library(dbplyr, warn.conflicts = FALSE)                                                             
con <- dbConnect(odbc(), "datawarehouse")                                                           
airports <- tbl(con, in_schema("production", "airports"))                                           
airports %>%                                                                                        
mutate(field = ifelse(name %in% c("test1", "test2", "Lansdowne Airport"), "string1", "string2")) %>%
select(name, field) %>%                                                                             
head()                                                                                              
#> # Source:   lazy query [?? x 2]
#> # Database: Microsoft SQL Server
#> #   14.00.1000[dbo@DESKTOP-10DBTVP\SQLEXPRESS/datawarehouse]
#>   name                           field  
#>   <chr>                          <chr>  
#> 1 Lansdowne Airport              string1
#> 2 Moton Field Municipal Airport  string2
#> 3 Schaumburg Regional            string2
#> 4 Randall Airport                string2
#> 5 Jekyll Island Airport          string2
#> 6 Elizabethton Municipal Airport string2
airports %>%                                                                                        
filter(name %in% c("test1", "test2", "Lansdowne Airport"))                                          
#> # Source:   lazy query [?? x 8]
#> # Database: Microsoft SQL Server
#> #   14.00.1000[dbo@DESKTOP-10DBTVP\SQLEXPRESS/datawarehouse]
#>   faa   name                lat   lon   alt    tz dst   tzone           
#>   <chr> <chr>             <dbl> <dbl> <int> <dbl> <chr> <chr>           
#> 1 04G   Lansdowne Airport  41.1 -80.6  1044    -5 A     America/New_York
airports %>%                                                                                        
mutate(field = ifelse(nchar(name) > 22, "a", "b")) %>%                                              
select(field, name) %>%                                                                             
head()                                                                                              
#> # Source:   lazy query [?? x 2]
#> # Database: Microsoft SQL Server
#> #   14.00.1000[dbo@DESKTOP-10DBTVP\SQLEXPRESS/datawarehouse]
#>   field name                          
#>   <chr> <chr>                         
#> 1 b     Lansdowne Airport             
#> 2 a     Moton Field Municipal Airport 
#> 3 b     Schaumburg Regional           
#> 4 b     Randall Airport               
#> 5 b     Jekyll Island Airport         
#> 6 a     Elizabethton Municipal Airport
airports  %>%                                                                                       
filter(nchar(name) > 22) %>%                                                                        
tally()                                                                                             
#> # Source:   lazy query [?? x 1]
#> # Database: Microsoft SQL Server
#> #   14.00.1000[dbo@DESKTOP-10DBTVP\SQLEXPRESS/datawarehouse]
#>       n
#>   <int>
#> 1   494
airports %>%                                                                                        
filter(!is.na(name)) %>%                                                                            
tally()                                                                                             
#> # Source:   lazy query [?? x 1]
#> # Database: Microsoft SQL Server
#> #   14.00.1000[dbo@DESKTOP-10DBTVP\SQLEXPRESS/datawarehouse]
#>       n
#>   <int>
#> 1  1458
airports %>%                                                                                        
filter(is.na(name)) %>%                                                                             
tally()                                                                                             
#> # Source:   lazy query [?? x 1]
#> # Database: Microsoft SQL Server
#> #   14.00.1000[dbo@DESKTOP-10DBTVP\SQLEXPRESS/datawarehouse]
#>       n
#>   <int>
#> 1     0
                                                                                                    
dbDisconnect(con)                     
```

### CODE REVIEW

**Comment by edgararuiz** [comment]
ptal @hadley

**Comment by edgararuiz** [comment]
Fixes #104

**Comment by bogdanrau** [comment]
@edgararuiz I owe you a beer at the next RStudio conference! I'll give it a test run on my end and ping you if I notice any issues. Thank you!

**Comment by ablack3** [comment]
Hi @edgararuiz, 
Thanks very much for making this fix. I tested it out and found one possible issue. case_when works when as long as there is no catch all condition at the end. Maybe this is a new issue. Just wanted to let you know. Thanks again for this fix though.

```

library(dplyr, warn.conflicts = F)
con <- DBI::dbConnect(odbc::odbc(), Driver = "SQL Server", Server = "test_server", Database = "test_db")
mtcars_db <- tbl(con, "mtcars")

mtcars_db %>%
  mutate(wt_grp = case_when(
    wt < 3 ~ "<3",
    wt < 4 ~ "[3,4)",
    wt < 5 ~ "[4,5)"
  )) %>%
  count(wt_grp)
#> # Source:   lazy query [?? x 2]
#> # Database: Microsoft SQL Server ************************
#>   wt_grp     n
#>   <chr>  <int>
#> 1 <NA>       3
#> 2 <3        12
#> 3 [3,4)     16
#> 4 [4,5)      1

mtcars_db %>%
  mutate(wt_grp = case_when(
    wt < 3 ~ "<3",
    wt < 4 ~ "[3,4)",
    wt < 5 ~ "[4,5)",
    TRUE ~ ">5"
  )) %>%
  count(wt_grp)
#> Error: <SQL> 'SELECT  TOP 10 "wt_grp", COUNT(*) AS "n"
#> FROM (SELECT "mpg", "cyl", "disp", "hp", "drat", "wt", "qsec", "vs", "am", "gear", "carb", CASE
#> WHEN ("wt" < 3.0) THEN ('<3')
#> WHEN ("wt" < 4.0) THEN ('[3,4)')
#> WHEN ("wt" < 5.0) THEN ('[4,5)')
#> WHEN (TRUE) THEN ('>5')
#> END AS "wt_grp"
#> FROM "mtcars") "yzponecopu"
#> GROUP BY "wt_grp"'
#>   nanodbc/nanodbc.cpp:****: *****: [Microsoft][ODBC SQL Server Driver][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'THEN'.
```

**Comment by ablack3** [comment]
One more breaking change I think I found. This code seemed to work with the version of dbplyr on cran but not when I use this branch.

``` r

library(dplyr)
con <- DBI::dbConnect(odbc::odbc(), Driver = "SQL Server", Server = "test_server", Database = "test_db")
mtcars_db <- tbl(con, "mtcars")
mtcars_db %>% 
  mutate(missing_mpg = ifelse(is.na(mpg), "missing", "not missing"))
#> Error: $ operator is invalid for atomic vectors
```

<sup>Created on 2018-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

File: R/db-odbc-mssql.R [hunk 1]
```diff
@@ -223,11 +209,17 @@ mssql_generic_infix <- function(if_select, if_filter) {
 }
 
 mssql_sql_if <- function(cond, if_true, if_false = NULL) {
+
+  old <- sql_current_context()
```
Comment (hadley) [inline R/db-odbc-mssql.R]: I think these you should the `on.exit()` pattern here:

```R
old <- sql_current_context()
on.exit(sql_current_context(old), add = TRUE)
```

But I don't understand how this code works because I don't see you checking that the context is "ifelse" anywhere.

Comment (edgararuiz) [reply R/db-odbc-mssql.R]: Yes, this was to prevent current context from returning "SELECT" or "ORDER".  My initial thought was to invent an overriding value in case it needs to be used later for something else. But, while I was re-reading my code and trying to remember what I did, the "ifelse" value does cause confusion.  Replaced it with `list(clause = "")`.  This also solves @ablack3 's issue reported here: https://github.com/tidyverse/dbplyr/pull/103#issuecomment-431481889

**Comment by edgararuiz** [comment]
> Overall strategy seems sound. Can you please also add a test case for an input that previously generated incorrect SQL but now works?

Yes, here are a couple:

Before:

```
airports %>%                                                                                        
  mutate(field = ifelse(name %in% c("test1", "test2", "Lansdowne Airport"), "string1", "string2")) %>%
  select(name, field) %>%                                                                             
  head()                                                                                              
#> Error: <SQL> 'SELECT  TOP 6 "name", "field"
#> FROM (SELECT "faa", "name", "lat", "lon", "alt", "tz", "dst", "tzone", CASE WHEN (("name" IN ('test1', 'test2', 'Lansdowne Airport')) =  'TRUE') THEN ('string1') WHEN (("name" IN ('test1', 'test2', 'Lansdowne Airport')) =  'FALSE') THEN ('string2') END AS "field"
#> FROM "airports") "ojcffameyd"'
#>   nanodbc/nanodbc.cpp:1587: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near '='.

airports %>%                                                                                        
  mutate(field = case_when(is.na(name) ~ "na", !is.na(name) ~ "notna", TRUE ~ "rest") ) %>%
  select(field) %>%
  head()
#> Error: <SQL> 'SELECT  TOP 6 "field"
#> FROM (SELECT "faa", "name", "lat", "lon", "alt", "tz", "dst", "tzone", CASE
#> WHEN (CONVERT(BIT, IIF("name" IS NULL, 1, 0))) THEN ('na')
#> WHEN (~(CONVERT(BIT, IIF("name" IS NULL, 1, 0)))) THEN ('notna')
#> WHEN (TRUE) THEN ('rest')
#> END AS "field"
#> FROM "airports") "unxngylzat"'
#>   nanodbc/nanodbc.cpp:1587: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'THEN'.
```

After:

```
airports %>%                                                                                        
  mutate(field = ifelse(name %in% c("test1", "test2", "Lansdowne Airport"), "string1", "string2")) %>%
  select(name, field) %>%                                                                             
  head()                                                                                              
#> # Source:   lazy query [?? x 2]
#> # Database: Microsoft SQL Server
#> #   14.00.1000[dbo@LAPTOP-368HS2ML\SQLEXPRESS/datawarehouse]
#>   name                           field  
#>   <chr>                          <chr>  
#> 1 Lansdowne Airport              string1
#> 2 Moton Field Municipal Airport  string2
#> 3 Schaumburg Regional            string2
#> 4 Randall Airport                string2
#> 5 Jekyll Island Airport          string2
#> 6 Elizabethton Municipal Airport string2

airports %>%                                                                                        
  mutate(field = case_when(is.na(name) ~ "na", !is.na(name) ~ "notna", TRUE ~ "rest") ) %>%
  select(field) %>%
  head()
#> # Source:   lazy query [?? x 1]
#> # Database: Microsoft SQL Server
#> #   14.00.1000[dbo@LAPTOP-368HS2ML\SQLEXPRESS/datawarehouse]
#>   field
#>   <chr>
#> 1 notna
#> 2 notna
#> 3 notna
#> 4 notna
#> 5 notna
#> 6 notna
```

**Comment by hadley** [comment]
I was thinking of a simple sql generation test along the lines of the ones you modified.

File: R/db-odbc-mssql.R (hunk 1 above)
Comment (hadley) [reply R/db-odbc-mssql.R]: Sorry, I typed the pattern slightly incorrectly - it should be:

```R
old <- set_current_context(list(clause = ""))
on.exit(sql_current_context(old), add = TRUE)
```

If that doesn't work `set_current_context()` needs to be modified to invisibly return the previous value.

File: R/translate-sql-base.r [hunk 2]
```diff
@@ -343,13 +343,20 @@ sql_case_when <- function(...) {
   query <- vector("list", n)
   value <- vector("list", n)
 
+  # Sets context to ifelse so infix operations, such as & are
```
Comment (hadley) [inline R/translate-sql-base.r]: This comment should either be in every copy of this pattern, or nowhere.

File: R/translate-sql-base.r [hunk 3]
```diff
@@ -343,13 +343,20 @@ sql_case_when <- function(...) {
...
+  set_current_context(list(clause = ""))
   for (i in seq_len(n)) {
     f <- formulas[[i]]
 
     env <- environment(f)
     query[[i]] <- escape(eval_bare(f[[2]], env), con = sql_current_con())
     value[[i]] <- escape(eval_bare(f[[3]], env), con = sql_current_con())
   }
+  # Restores context
+  set_current_context(old)
```
Comment (hadley) [inline R/translate-sql-base.r]: This is no longer needed with the `on.exit()` pattern.

File: R/db-odbc-mssql.R (hunk 1 above)
Comment (hadley) [reply R/db-odbc-mssql.R]: This still isn't quite right - you have three lines of code instead of two.

File: R/db-odbc-mssql.R [hunk 4]
```diff
@@ -223,11 +209,17 @@ mssql_generic_infix <- function(if_select, if_filter) {
...
+  on.exit(set_current_context(old), add = TRUE)
+  set_current_context(list(clause = ""))
+  cond <- build_sql(cond)
+
   build_sql(
```
Comment (hadley) [inline R/db-odbc-mssql.R]: Just wondering: can we just just call `sql_if()` here?

Comment (edgararuiz) [reply R/db-odbc-mssql.R]: That function lacks the `else` step I had to add to this function so that the first case I posted in the before-and-after comment works.  Didn't want to change `sql_if()` because of I'm not sure if it would mess up anything for the other translations.

Comment (hadley) [reply R/db-odbc-mssql.R]: That doesn't seem right to me — you shouldn't be adding an else block that returns an empty string.

Comment (edgararuiz) [reply R/db-odbc-mssql.R]: Idk what happened, I swear I tested it before replying this morning.  I tried switching to `sql_if()` again to trace the error, but everything worked :) Sorry for the confusion, I'll attribute it to lack of coffee
