### PR TITLE
Fix td translations

### LINKED ISSUE #1544: Teradata incorrect sql_translation for scalar "as.double" and "as.character"
Greetings, 

In the backend translations for Teradata, the [function sql_translation.Teradata](https://github.com/tidyverse/dbplyr/blob/1ff6363437c3ce9292a1c7c3b37a4073965bb2ec/R/backend-teradata.R#L98C17-L98C26) has 2 wrong translations, for the base R function as.double() and as.character(). 

# as.double()

The translation uses NUMERIC which errors because the correct SQL function for Teradata is FLOAT

```r
con <- dbplyr::simulate_teradata()

tbl_test <- dbplyr::tbl_lazy(mtcars, con = con, name = "mtcars_td")

tbl_test |> 
  dplyr::select(mpg, cyl) |> 
  dplyr::mutate(mpg = as.double(mpg)) |> 
  dplyr::show_query()
```

Result : 

```
<SQL>
SELECT CAST(`mpg` AS NUMERIC) AS `mpg`, `cyl`
FROM `mtcars_td`
```

The output should be 

```
<SQL>
SELECT CAST(`mpg` AS FLOAT) AS `mpg`, `cyl`
FROM `mtcars_td`
```

The sql_translation.Teradata should have `sql_cast("FLOAT")`  instead of `sql_cast("NUMERIC")`. The odbc package further helps validating this as the translation there for type double is FLOAT in Teradata.  

To rectify, I've successfully modified the sql_translation.Teradata function with the above mentionned change and the fork works correctly now on our TD backend.

# as.character()

The translation uses VARCHAR(MAX) which errors because the correct SQL function for Teradata is VARCHAR(N) where N must be a number, usually by default 255.

```r
con <- dbplyr::simulate_teradata()

tbl_test <- dbplyr::tbl_lazy(mtcars, con = con, name = "mtcars_td")

tbl_test |> 
  dplyr::select(mpg, cyl) |> 
  dplyr::mutate(mpg = as.character(cyl)) |> 
  dplyr::show_query()
```

Result : 

```
<SQL>
SELECT `mpg`, CAST(`cyl` AS VARCHAR(MAX)) AS `cyl`
FROM `mtcars_td`
```

The output should be, e.g : 

```
<SQL>
SELECT `mpg`, CAST(`cyl` AS VARCHAR(255)) AS `cyl`
FROM `mtcars_td`
```

The sql_translation.Teradata should have at minimum `sql_cast("VARCHAR(255)")`  instead of `sql_cast("VARCHAR(MAX)")`. The odbc package further helps validating this as the translation there for type character is VARCHAR(255).  

To rectify, I've successfully modified the sql_translation.Teradata function with the above mentionned change and the fork works correctly now on our TD backend. I've also upgraded the function to mimic the behavior of as.numeric() which allows the user to specify the argument for digits, and allow the user to specify the length of VARCHAR(N)

```r
sql_translation.Teradata <- function(con) {
  sql_variant(
    sql_translator(.parent = base_odbc_scalar,
      # Other scalars removed for ease of reading
      as.character  = function(x, nchar = 255L) {
        nchar <- vctrs::vec_cast(nchar, integer())
        sql_expr(CAST(!!x %as% VARCHAR(!!nchar)))
      },
   # Rest of function body
  )
)
```

I hope this is clear enough, thank you for your time, and I can provide a PR for this if that's how things work. I'm still very new to contributing so please bear with me and don't hesitate to tell me what I did wrong !

Cheers, 

Raphael

### PR DESCRIPTION
**Pull request by rplsmn**
Fixed as.character and as.double for Teradata

### CODE REVIEW

**Comment by simonpcouch** [comment]
Intended to close #1544.

@rplsmn, thanks for the thorough issue description there! It appears you've closed this PR—did you intend to do so? If so, would you be interested in working together to get those checks passing and the PR merged?

**Comment by rplsmn** [comment]
Hello,

I had opened this PR by mistake while trying to open a PR elsewhere, and since it happened before anyone gave me the permission on my issue I felt like I was being very impolite so I closed it until someone gave me the green light :) 
Should I reopen it then ? 
I'm very interested in working together on this, yes !

**Comment by rplsmn** [comment]
Hi, I'm just checking in to ask if I forgot something here ? 
I understand that these things take time, there is no rush and this is not a message to get anyone to react faster !
This is my first real PR so I don't want it to be hanging because of a mistake on my side.

**Review by simonpcouch — APPROVED** [review]
> Hi, I'm just checking in to ask if I forgot something here ?

Nope, all good! Just took me a bit to get to it.

These changes look solid to me. I'm approving merge, but going to ping another reviewer internally before doing so.

File: R/backend-teradata.R [hunk 1]
```diff
@@ -109,8 +109,11 @@ sql_translation.Teradata <- function(con) {
                         digits <- vctrs::vec_cast(digits, integer())
                         sql_expr(CAST(!!x %as% DECIMAL(12L, !!digits)))
                       },
-      as.double     = sql_cast("NUMERIC"),
-      as.character  = sql_cast("VARCHAR(MAX)"),
+      as.double     = sql_cast("FLOAT"),
+      as.character  = function(x, nchar = 255L) {
+        nchar <- vctrs::vec_cast(nchar, integer())
```
Comment (hadley) [inline R/backend-teradata.R:114]: This doesn't feel quite right because I think you want `nchar` to be a scalar? So `check_number_whole()` would be more appropriate here (but I don't know if we have that in dbplyr yet). @simonpcouch should be able to help (otherwise this PR looks good to me at least within the limitation of my SQL knowledge 😄)

Comment (simonpcouch) [inline R/backend-teradata.R:114]:
```suggestion
        check_number_whole(nchar, min = 0, max = 255)
```

Yup, we do have the type checkers! This change should do the trick, @rplsmn—once you've accepted it and checks pass, this PR will be good to go.

Comment (simonpcouch) [reply R/backend-teradata.R:114]: [Reference for that 64,000 value](https://www.sfu.ca/sasdoc/sashtml/accdb/z1250040.htm#:~:text=character%20string%20data.-,The%20maximum%20for%20n%20is%2064%2C000.,also%20known%20as%20CHARACTER%20VARYING.&text=specifies%20a%20varying%2Dlength%20column%2C%20of%20the%20maximum%20length%2C,version%20your%20server%20is%20running.).

**Comment by rplsmn** [comment]
Hello, I hope I clicked in the right places ! 
Thank you
