### PR TITLE
Refine `select` inline criteria to keep `arrange`d computed columns

### LINKED ISSUE #1437: `select()` fails after specific sequence of `dplyr` commands
It seems that when you sequence a `group_by()`, then a `mutate()`, and lastly an `arrange()`, `dbplyr` is not able to find the variable created by the `mutate()` when using `select()`. This works against a regular data frame. Reprex here:

``` r
suppressPackageStartupMessages(library(dplyr)) 
suppressPackageStartupMessages(library(dbplyr))
memdb_frame(
  Name = c("Alice", "Bob", "Alice", "Bob", "Charlie"),
  Subject = c("Math", "Math", "English", "English", "Math"),
  Score = c(90, 85, 88, 92, 78)
) %>% 
  group_by(Name) %>% 
  mutate(AvgScore = 1) %>% 
  ungroup() %>% 
  arrange(AvgScore, Name) %>% 
  select(Name)
#> Error in `collect()`:
#> ! Failed to collect lazy table.
#> Caused by error:
#> ! no such column: AvgScore
```

<sup>Created on 2024-01-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Initially reported as a possible bug in `sparklyr` here: https://github.com/sparklyr/sparklyr/issues/3413

### PR DESCRIPTION
**Pull request by ejneer**
Fixes #1437

This will stop `arrange`d computed columns from being inlined away from subqueries. Of course the subquery `ORDER BY` warning will be thrown, but I think that is expected behavior.

Before:

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

db <- lazy_frame(x = 1, y = 2) 

db %>% 
  mutate(z = 1) %>% 
  arrange(x, z) %>%
  select(x)
#> <SQL>
#> SELECT `x`
#> FROM `df`
#> ORDER BY `x`, `z`
```

<sup>Created on 2024-02-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

After:

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

db <- lazy_frame(x = 1, y = 2) 

db %>% 
  mutate(z = 1) %>% 
  arrange(x, z) %>%
  select(x)
#> Warning: ORDER BY is ignored in subqueries without LIMIT
#> ℹ Do you need to move arrange() later in the pipeline or use window_order() instead?
#> <SQL>
#> SELECT `x`
#> FROM (
#>   SELECT `df`.*, 1.0 AS `z`
#>   FROM `df`
#> ) AS `q01`
```

<sup>Created on 2024-02-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

File: R/verb-select.R [hunk 1]
```diff
@@ -131,6 +131,28 @@ add_select <- function(lazy_query, vars) {
...
+
+  computed_columns <- purrr::pmap(
+    lazy_query$select,
+    function(name, expr, ...) if (is_quosure(expr)) name
+  ) %>%
+    purrr::compact()
+
+  order_vars <- purrr::map_chr(lazy_query$order_by, as_label)
+
+  all(
```
Comment (hadley) [inline R/verb-select.R:148]: Given there's only two clauses here, I think `&&` would be easier to understand.

File: R/verb-select.R [hunk 2]
```diff
@@ -131,6 +131,28 @@ add_select <- function(lazy_query, vars) {
   )
 }
 
+select_can_be_inlined <- function(lazy_query, vars) {
+  vars_data <- op_vars(lazy_query)
+
+  bijective_or_not_distinct <- is_bijective_projection(vars, vars_data) ||
+      !is_true(lazy_query$distinct)
+
```
Comment (hadley) [inline R/verb-select.R:139]: I'd probably not name this (since the variable name is rather long and only used in one place) and instead inline in the logical expression below.

**Comment by hadley** [comment]
Thanks for taking a stab at this!

**Comment by hadley** [comment]
@mgirlich could you please take a look at this PR too

File: R/verb-select.R [hunk 3]
```diff
@@ -131,6 +131,23 @@ add_select <- function(lazy_query, vars) {
...
 }
 
+select_can_be_inlined <- function(lazy_query, vars) {
+  vars_data <- op_vars(lazy_query)
+
+  computed_columns <- purrr::pmap(
+    lazy_query$select,
+    function(name, expr, ...) if (is_quosure(expr)) name
+  ) %>%
+    purrr::compact()
```
Comment (mgirlich) [inline R/verb-select.R:141]:
```suggestion
  computed_flag <- purrr::map_lgl(lazy_query$select$expr, is_quosure)
  computed_columns <- lazy_query$select$name[computed_flag]
```

This is short and a bit more clear. Also this makes sure that `computed_columns` is actually a character vector, not a list.

File: tests/testthat/_snaps/verb-select.md [hunk 4]
```diff
@@ -181,6 +181,22 @@
...
+      Warning:
+      ORDER BY is ignored in subqueries without LIMIT
+      i Do you need to move arrange() later in the pipeline or use window_order() instead?
+    Output
+      <SQL>
+      SELECT `x`
+      FROM (
+        SELECT `df`.*, 1.0 AS `z`
+        FROM `df`
+      ) AS `q01`
```
Comment (mgirlich) [inline tests/testthat/_snaps/verb-select.md:198]: To me the snapshot doesn't look like it fits to the title of the test. Can you come up with a test that tests the intended behaviour more directly?

**Review by mgirlich — APPROVED** [review]

File: tests/testthat/_snaps/verb-select.md (hunk 4 above)
Comment (ejneer) [reply tests/testthat/_snaps/verb-select.md:198]: This is just supposed to show that the subquery hasn't been removed. Do you think it should not be a snapshot test, or that should have a more descriptive title. If the latter, how about "Computed columns used to arrange are not removed by subsequent selects"?

Comment (mgirlich) [reply tests/testthat/_snaps/verb-select.md:198]: I think if I would come back to this test in a year and see the snapshot I wouldn't understand if the snapshot is correct or not. So, probably it shouldn't be a snapshot.

You could test the optimisation more directly, e.g.

```r
  out <- lf %>% mutate(z = 1) %>% arrange(x, z) %>% select(x)
  
  # 
  inner_query <- out$lazy_query$x
  expect_s3_class(inner_query, "lazy_select_query")
  expect_equal(
    inner_query$order_by,
    list(quo(x), quo(z)),
    ignore_formula_env = TRUE
  )

  expect_equal(op_vars(inner_query), c("x", "y", "z"))
  expect_equal(op_vars(out$lazy_query), "x")
```

and maybe also compare this to `lf %>% mutate(z = 1) %>% arrange(x, z) %>% select(x, z)`, i.e. a case where the inline optimisation was applied.

Comment (ejneer) [reply tests/testthat/_snaps/verb-select.md]: appreciate the pointers!

File: R/verb-select.R [hunk 5]
```diff
@@ -131,9 +131,20 @@ add_select <- function(lazy_query, vars) {
   )
 }
 
-is_bijective_projection <- function(vars, names_prev) {
-  vars <- unname(vars)
-  identical(sort(vars), names_prev)
+select_can_be_inlined <- function(lazy_query, vars) {
```
Comment (hadley) [inline R/verb-select.R:134]: I made a few tweaks here to hopefully make the logic a bit clearer.

File: tests/testthat/test-verb-select.R [hunk 6]
```diff
@@ -35,6 +35,31 @@ test_that("select after distinct produces subquery", {
   expect_true(lq$x$distinct)
 })
 
+test_that("select after arrange produces subquery, if needed", {
+  lf <- lazy_frame(x = 1)
+
+  # shouldn't inline
+  out <- lf %>% mutate(z = 2) %>% arrange(x, z) %>% select(x)
```
Comment (hadley) [inline tests/testthat/test-verb-select.R:42]: I'm not sure this is testing the right thing because when I run it, I see:

```
SELECT `x`
FROM (
  SELECT `df`.*, 2.0 AS `z`
  FROM `df`
) AS `q01`
Warning message:
ORDER BY is ignored in subqueries without LIMIT
ℹ Do you need to move arrange() later in the pipeline or use window_order() instead? 
```

Comment (hadley) [reply tests/testthat/test-verb-select.R:42]: Or maybe that is the expected behaviour? But definitely worth a snapshot test, I think.

Comment (ejneer) [reply tests/testthat/test-verb-select.R:42]: Yeah that is expected. I've re-added the snapshot I removed in my prior commit.

**Comment by hadley** [comment]
Thanks for your work on this @ejneer — it's much appreciated!
